name: Test Rational Project

on: [push]

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Java JDK
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Test with Ant
          run: ant -noinput -buildfile Rational/build.xml test
