name: Test Rational Project

on: [push]

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2.3.5
        - name: Setup Java JDK
          uses: actions/setup-java@v2.3.1
          with:
            java-version: '17'
            distribution: 'adopt'
        - name: Test with Ant
          run: ant test
